CREATE OR REPLACE PROCEDURE brh.insere_projeto (
    p_ID VARCHAR, p_PROJETO VARCHAR, p_NOME VARCHAR, p_RESPONSAVEL VARCHAR, p_INICIO DATE )
    
IS
BEGIN
    INSERT INTO PROJETO (ID, NOME, RESPONSAVEL, INICIO);
    VALUES (p_ID, p_NOME, p_RESPONSAVEL, p_INICIO);
    
    COMMIT;

END;

//TAREFA 2

CREATE OR REPLACE PROCEDURE BRH.INSERE_PROJETO (
    p_PROJETO VARCHAR, p_PROJETO VARCHAR, p_id VARCHAR, p_INICIO DATE,p_FIM DATE
)
IS
    V_DURACAO_MESES NUMBER;
BEGIN
    // CALCULAR A DIFERENÇA EM MESES ENTRE AS DATAS DE INÍCIO E FIM
    V_DURACAO_MESES := MONTHS_BETWEEN(DATA_FIM_PROJETO, DATA_INICIO_PROJETO);

    // INSERIR OS DADOS NA TABELA BRH.PROJETOS, INCLUINDO A DURAÇÃO EM MESES
    INSERT INTO BRH.PROJETOS (NOME, RESPONSAVEL, MATRICULA, INICIO, FIM, DURACAO_MESES)
    VALUES (NOME, RESPONSAVEL, ID, INICIO, FIM, V_DURACAO_MESES);
    
    COMMIT;
EXCEPTION
   
END;

// Crie a function brh.calcula_idade, que informa a idade a partir de uma data

SELECT MONTHS_BETWEEN 
   (TO_DATE('02-02-1995','MM-DD-YYYY'),
    TO_DATE('01-01-1995','MM-DD-YYYY') ) "Months"
    FROM DUAL;

SELECT * FROM DEPENDENTE

SELECT TO CHAR(DATA_NASCIMENTO,'MM' FROM DEPENDENTE);

SELECT * FROM PROJETO;

SELECT MONTHS_BETWEEN 
   (TO_INICIO, TO_FIM )FROM PROJETO;
   
 //  Crie a function brh.finaliza_projeto para registrar o término da execução de um projeto:



CREATE OR REPLACE PROCEDURE brh.insere_projeto (
    p_ID VARCHAR, p_PROJETO VARCHAR, p_NOME VARCHAR, p_RESPONSAVEL VARCHAR, p_INICIO DATE )
    
IS
BEGIN
    INSERT INTO PROJETO (ID, NOME, RESPONSAVEL, INICIO);
    VALUES (p_ID, p_NOME, p_RESPONSAVEL, p_INICIO);
    
    COMMIT;

END;

